[credentials]
usernames = { admin = {failed_login_attempts = 0,  logged_in = false, name = "Admin", password = "123"}, rbriggs = {failed_login_attempts = 0,  logged_in = false, name = "admin2", password = "abc"}}

[cookie]
expiry_days = 30
key = "some_signature_key"  # Must be string
name = "some_cookie_name"
